#!/bin/bash

#************************************************************#
#                          Locate                            #
#                            by                              #
#                  Debanjum Singh Solanky                    #
#                    February 22, 2014                       #
#                                                            #
#         Retrieve Current Location from DuckDuckGo          #
#                       ./Locate_DDG                         #
#************************************************************#

# INITIALISING VARIABLES
scriptsdir='./Location'		         #SETTING LOCATION SCRIPTS DIRECTORY
location="$scriptsdir/location"         	 #SETTING CURRENT LOCATION FILE
iconsdir="$scriptsdir/Icons"  		         #SETTING ICONS DIRECTORY
notifyicon="$iconsdir/location.svg"     	 #SETTING DEFAULT NOTIFICATION ICON LOCATION
hour=$(date +%H)     		                 #EVALUATING CURRENT LOCAL TIME


# VALID ARGUMENTS
[ $# -eq 0 ] && (

# LOCATION UPDATING NOTIFICATION
# notify-send "Locating" "..." -i "$notifyicon" -t 500 --hint string:transient:1

# BACKING UP OLD LOCATION
`mv "$scriptsdir/location" "$scriptsdir/location_old"`

# RETRIEVING CURRENT LOCATION REPORT[FROM DUCKDUCKGO]
wget -q -O "$scriptsdir/location" https://duckduckgo.com/?q=ip

# PARSING HTML TO EXTRACT LOCATION + ERROR CATCHING
city=`sed -n 's/^.*\(zero_click_abstract.*>\)\(.*\)<\/a>.*zero_click_abstract.*$/\2/p' "$scriptsdir/location"`
[[ "$city" = "" ]] && ( notify-send "Unable to Retrieve Latest Location" -i "$notifyicon" -t 100 --hint string:transient:1; `mv "$scriptsdir/location_old" "$scriptsdir/location"`)

# INSERT CURRENT LOCATION IN DROPBOX
city=`sed -n 's/^.*\(zero_click_abstract.*>\)\(.*\)<\/a>.*zero_click_abstract.*$/\2/p' "$scriptsdir/location"`
echo -n "$city" > ./Location/L.txt

# LATEST LOCATION NOTIFICATION
notify-send "Current Known Location" "$city @ $hour 00" -i "$notifyicon" -t 100 --hint string:transient:1
)
